### ISSUE TITLE
error when running python test_phases.py

### ISSUE THREAD

**Issue by espinielli** [junzis/flight-data-processor#2]
It looks like `test_phases.py` uses a [python 3.6  version of `pickle.load()`](https://docs.python.org/3/library/pickle.html) which accepts an `encoding` argument, while the [2.7 version does not](https://docs.python.org/2/library/pickle.html).

Here is the error I get when running `python test_phases.py` as in the README:

```shell
$ python test_phases.py
Traceback (most recent call last):
  File "test_phases.py", line 12, in <module>
    dataset = pickle.load(open(datadir+'/data/test_segment.pkl', 'rb'), encoding='bytes')
TypeError: load() got an unexpected keyword argument 'encoding'
(py27)
```
I tried to remove `encoding='bytes'` but I get further issues (after I close the plots from `flightphase.plot_logics()`):

```shell
$ python test_phases.py
Traceback (most recent call last):
  File "test_phases.py", line 12, in <module>
    dataset = pickle.load(open(datadir+'/data/test_segment.pkl', 'rb'))
  File "C:\opt\Miniconda3\envs\py27\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "C:\opt\Miniconda3\envs\py27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\opt\Miniconda3\envs\py27\lib\pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "C:\opt\Miniconda3\envs\py27\lib\pickle.py", line 1130, in find_class
    __import__(module)
ImportError: No module named datetime
(py27)
```

**Comment by junzis** [comment]
I update the code some time ago to only support Python 3. The pickle example is packed using python3, which I don't think it would work in python2.  Just changed the requirements in README. 

The other issue you open is also because of the python version. I am trying to not to write Python 2 code anymore. It's about time :-)

**Comment by espinielli** [comment]
In a clean environment as in #1 I do get one window with the plots...
